version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: "gunicorn SymplyFinance.wsgi 0.0.0.0:8000"
    volumes:
      - .:/app
    container_name: symply
    image: symplyfi
