name: CI for SymplyFinance

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 
        uses: actions/setup-python@v4
        with:
          python-version:  "3.11"
          cache: 'pip' # caching pip dependencies


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run the test
        run: |
          python3 manage.py test
      
      # - name: Build Docker image
      #   run: docker build -t simplyfinance-image .
        
      # - name: Run the test using Docker
      #   run: docker run simplyfinance-image python3 manage.py test
    
          